version: '3'

services:
  jupyter:
    build:
      context: .
      dockerfile: images/jupyter-lab/Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/app
    ports:
      - "8090:8888"
    command: jupyter lab --allow-root --ip 0.0.0.0 --port=8888 --no-browser --notebook-dir=/app --NotebookApp.token=rndbox
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  ollama:
    build:
      context: .
      dockerfile: images/ollama/Dockerfile
    container_name: ollama
    volumes:
      - "./ollama_files:/root/.ollama"
    ports:
      - "11434:11434"

volumes:
  ollama_files:
