version: '3'

services:
  jupyter:
    build:
      context: .
    env_file:
      - ./.env
    volumes:
      - .:/app
    ports:
      - "8090:8888"
    command: jupyter lab --allow-root --ip 0.0.0.0 --port=8888 --no-browser --notebook-dir=/app --NotebookApp.token=rndbox
